const GET_COMMENTS_BEGIN = 'GET_COMMENTS_BEGIN';
const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
const POST_COMMENTS_SUCCESS = 'POST_COMMENTS_SUCCESS';
const COMMENTS_SEARCH = 'COMMENTS_SEARCH';
const GET_ERROR = 'GET_ERROR';


export default {
    GET_COMMENTS_BEGIN,
    GET_COMMENTS_SUCCESS,
    POST_COMMENTS_SUCCESS,
    COMMENTS_SEARCH,
    GET_ERROR,
};